name: Build Extension

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install Ant
      run: sudo apt-get install ant

    - name: Build Extension
      run: ant extensions

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Base64Mahrus-AIX
        path: out/*.aix
